routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('/item', 'ItemController');
Route::resource('/uom', 'UnitController');
Route::resource('/supplier', 'SupplierController');
Route::resource('/purchase', 'PurchaseController');
Route::resource('/customer', 'CustomerController');
Route::resource('/sales', 'SalesController');
Route::get('/purchase-outstanding','PurchaseController@purchaseOutstanding');
Route::get('/purchase/{id}/print', 'PurchaseController@purchasePrint');
Route::get('/invoice/{id}/print', 'InvoiceController@invoicePrint');
Route::get('/sales-outstanding', 'SalesController@salesOutstanding');
Route::get('/payment-transaction','HomeController@paymentTransaction');
Route::resource('/invoices', 'InvoiceController');
Route::resource('/bills', 'BillController');

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    protected $fillable = [
        'sales_no', 'sales_date', 'due_date',
        'title', 'sub_total', 'discount',
        'grand_total', 'sales_tnc', 'sales_note', 'sales_delivery_method', 'sales_person', 'sales_reference', 'sales_order', 'sales_customer_name',
        'client_address'
    ];

    public function products()
    {
        return $this->hasMany(SaleProduct::class);
    }
}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Sale;
use App\SaleProduct;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SalesController extends Controller
{
    public function index()
    {
        $sales = Sale::orderBy('created_at', 'desc')
            ->paginate(8);

        return view('sales.index', compact('sales'));
    }

    public function create()
    {
        $suppliers = DB::table('suppliers')
            ->select('supplier_name')
            ->where('deleted_at', '=', null)
            ->get();
        $customers = DB::table('customers')
            ->select('customer_name')
            ->where('deleted_at', '=', null)
            ->get();
        $items = DB::table('items')
            ->select('item_name', 'item_sales_selling_price', 'item_purchase_selling_price', 'item_sales_tax')
            ->where('deleted_at', '=', null)
            ->get();
        return view('sales.create', compact('suppliers', 'customers', 'items'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'sales_no' => 'required|alpha_dash|unique:sales',
            'sales_delivery_method' => 'required|max:255',
            'sales_person' => 'required|max:255',
            'sales_reference' => 'required|max:255',
            'sales_order' => 'required|max:255',
            'sales_customer_name' => 'required|max:255',
            'client_address' => 'required|max:255',
            'sales_date' => 'required|date_format:Y-m-d',
            'due_date' => 'required|date_format:Y-m-d',
            'title' => 'required|max:255',
            'discount' => 'required|numeric|min:0',
            'products.*.name' => 'required|max:255',
            'products.*.price' => 'required|numeric|min:1',
            'products.*.qty' => 'required|integer|min:1'
        ]);

        $products = collect($request->products)->transform(function ($product) {
            $product['total'] = $product['qty'] * $product['price'];
            return new SaleProduct($product);
        });

        if ($products->isEmpty()) {
            return response()
                ->json([
                    'products_empty' => ['One or more Product is required.']
                ], 422);
        }

        $data = $request->except('products');
        $data['sub_total'] = $products->sum('total');
        $data['grand_total'] = $data['sub_total'] - $data['discount'];

        $sale = Sale::create($data);

        $sale->products()->saveMany($products);

        return response()
            ->json([
                'created' => true,
                'id' => $sale->id
            ]);
    }

    public function show($id)
    {
        $sale = Sale::with('products')->findOrFail($id);
        return view('sales.show', compact('sale'));
    }

    public function edit($id)
    {
        $suppliers = DB::table('suppliers')
            ->select('supplier_name')
            ->where('deleted_at', '=', null)
            ->get();
        $customers = DB::table('customers')
            ->select('customer_name')
            ->where('deleted_at', '=', null)
            ->get();
        $items = DB::table('items')
            ->select('item_name', 'item_sales_selling_price', 'item_purchase_selling_price', 'item_sales_tax')
            ->where('deleted_at', '=', null)
            ->get();
        $sale = Sale::with('products')->findOrFail($id);
        return view('sales.edit', compact('sale', 'suppliers', 'customers', 'items'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'sales_no' => 'required|alpha_dash|unique:sales,sales_no,' . $id . ',id',
            'sales_delivery_method' => 'required|max:255',
            'sales_person' => 'required|max:255',
            'sales_reference' => 'required|max:255',
            'sales_order' => 'required|max:255',
            'sales_customer_name' => 'required|max:255',
            'client_address' => 'required|max:255',
            'sales_date' => 'required|date_format:Y-m-d',
            'due_date' => 'required|date_format:Y-m-d',
            'title' => 'required|max:255',
            'discount' => 'required|numeric|min:0',
            'products.*.name' => 'required|max:255',
            'products.*.price' => 'required|numeric|min:1',
            'products.*.qty' => 'required|integer|min:1'
        ]);

        $sale = Sale::findOrFail($id);

        $products = collect($request->products)->transform(function ($product) {
            $product['total'] = $product['qty'] * $product['price'];
            return new SaleProduct($product);
        });

        if ($products->isEmpty()) {
            return response()
                ->json([
                    'products_empty' => ['One or more Product is required.']
                ], 422);
        }

        $data = $request->except('products');
        $data['sub_total'] = $products->sum('total');
        $data['grand_total'] = $data['sub_total'] - $data['discount'];

        $sale->update($data);

        SaleProduct::where('sale_id', $sale->id)->delete();

        $sale->products()->saveMany($products);

        return response()
            ->json([
                'updated' => true,
                'id' => $sale->id
            ]);
    }

    public function destroy($id)
    {
        $sale = Sale::findOrFail($id);

        SaleProduct::where('sale_id', $sale->id)
            ->delete();

        $sale->delete();

        return redirect('/sales');
    }

    public function salesOutstanding()
    {
        return view('sales-outstanding.sales-outstandings');
    }
}

resources/views/sales/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div id="sales">
            <div class="panel panel-default" v-cloak>
                <div class="panel-heading">
                    <div class="clearfix">
                        <span class="panel-title">Create Sales</span>
                        <a href="/sales" class="btn btn-default pull-right">Back</a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('sales.form')
                </div>
                <div class="panel-footer">
                    <a href="/sales" class="btn btn-default">CANCEL</a>
                    <button class="btn btn-success" @click="create" :disabled="isProcessing">CREATE</button>
                </div>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
<script src="/js/vue.min.js"></script>
<script src="/js/vue-resource.min.js"></script>
<script type="text/javascript">
    Vue.http.headers.common['X-CSRF-TOKEN'] = '{{csrf_token()}}';

    window._form = {
        sales_no: '',
        sales_tnc: '',
        sales_note: '',
        sales_delivery_method: '',
        sales_person: '',
        sales_reference: '',
        sales_order: '',
        sales_customer_name: '',
        client: '',
        client_address: '',
        title: '',
        invoice_date: '',
        due_date: '',
        discount: 0,
        products: [{
            name: '',
            price: 0,
            qty: 1
        }]
    };
</script>
<script src="/js/sales.js"></script>
@endpush

resources/views/sales/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div id="sales">
            <div class="panel panel-default" v-cloak>
                <div class="panel-heading">
                    <div class="clearfix">
                        <span class="panel-title">Edit Sales</span>
                        <a href="/sales" class="btn btn-default pull-right">Back</a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('sales.form')
                </div>
                <div class="panel-footer">
                    <a href="/sales" class="btn btn-default">CANCEL</a>
                    <button class="btn btn-success" @click="update" :disabled="isProcessing">UPDATE</button>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
<script src="/js/vue.min.js"></script>
<script src="/js/vue-resource.min.js"></script>
<script type="text/javascript">
    Vue.http.headers.common['X-CSRF-TOKEN'] = '{{csrf_token()}}';
    /*window._form = {!!$sale -> toJson()!!}; //this is correct format*/
    window._form = {
    !!$sale - > toJson()
    !!
    }
    ;
</script>
<script src="/js/sales.js"></script>
@endpush

resources/views/sales/form.blade.php
<style>
    p {
        color: #ff0000;
    }
</style>
<div class="row">
    <div class="col-sm-4">
        <div class="form-group">
            <label>Customer Name</label>
            <select class="form-control" id="myselect" name="sales_customer_name" v-model="form.sales_customer_name">
                <option disabled>Select Customer</option>
                @foreach($customers as $customer)
                    <option>{{$customer->customer_name}}</option>
                @endforeach
                {{--<option value="secondoption">+ Add New</option>--}}
            </select>

            <p v-if="errors.sales_customer_name" class="error">@{{errors.sales_customer_name[0]}}</p>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Sales Order</label>
            <input type="text" name="sales_order" class="form-control"
                   placeholder="sales order number" v-model="form.sales_order">

            <p v-if="errors.sales_order" class="error">@{{errors.sales_order[0]}}</p>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Reference</label>
            <input type="text" name="sales_reference" class="form-control"
                   placeholder="sales Reference" v-model="form.sales_reference">

            <p v-if="errors.sales_reference" class="error">@{{errors.sales_reference[0]}}</p>
        </div>
        <div class="form-group">
            <label>Sales Person</label>
            <select class="form-control" name="sales_person" v-model="form.sales_person">
                <option disabled>Select Sales Person</option>
                @foreach($suppliers as $supplier)
                    <option>{{$supplier->supplier_name}}</option>
                @endforeach
            </select>

            <p v-if="errors.sales_person" class="error">@{{errors.sales_person[0]}}</p>
        </div>
        <div class="form-group">
            <label>Delivery Method</label>
            <select class="form-control" name="sales_delivery_method" v-model="form.sales_delivery_method">
                <option disabled selected>Select Delivery Method</option>
                <option>Cash On Delivery</option>
                <option>Card Payment</option>
                <option>Other</option>
            </select>

            <p v-if="errors.sales_delivery_method" class="error">@{{errors.sales_delivery_method[0]}}</p>
        </div>

        <div class="form-group">
            <label>Sales No.</label>
            <input type="text" class="form-control" v-model="form.sales_no">

            <p v-if="errors.sales_no" class="error">@{{errors.sales_no[0]}}</p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label>Client Address</label>
            <textarea class="form-control" v-model="form.client_address"></textarea>

            <p v-if="errors.client_address" class="error">@{{errors.client_address[0]}}</p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" v-model="form.title">

            <p v-if="errors.title" class="error">@{{errors.title[0]}}</p>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <label>Sales Date</label>
                <input type="date" class="form-control" v-model="form.sales_date">

                <p v-if="errors.sales_date" class="error">@{{errors.sales_date[0]}}</p>
            </div>
            <div class="col-sm-6">
                <label>Due Date</label>
                <input type="date" class="form-control" v-model="form.due_date">

                <p v-if="errors.due_date" class="error">@{{errors.due_date[0]}}</p>
            </div>
        </div>
    </div>
</div>
<hr>
<div v-if="errors.products_empty">
    <p class="alert alert-danger">@{{errors.products_empty[0]}}</p>
    <hr>
</div>
<table class="table table-bordered table-form">
    <thead>
    <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th>Qty</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="product in form.products">
        <td class="table-name" :class="{'table-error': errors['products.' + $index + '.name']}">
            {{--<textarea class="table-control" v-model="product.name"></textarea>--}}

            <select class="form-control" id="name" v-model="product.name">
                <option disabled>Please Select Item</option>
                @foreach($items as $item)
                    <option @click="selectItem" value="{{$item->item_sales_selling_price}}"
                    >{{$item->item_name}}</option>
                @endforeach
            </select>
        </td>
        <td class="table-price" :class="{'table-error': errors['products.' + $index + '.price']}">
            {{--<input type="text" class="table-control"  v-model="product.price">--}}
            <input type="text" class="form-control" v-model="product.price" id="price">
        </td>
        <td class="table-qty" :class="{'table-error': errors['products.' + $index + '.qty']}">
            <input type="text" class="form-control" v-model="product.qty">
        </td>
        <td class="table-total">
            <span class="table-text" id="total">@{{product.qty * product.price}}</span>
        </td>
        <td class="table-remove">
            <span @click="remove(product)" class="table-remove-btn"><i class="fa fa-trash-o"
                                                                       aria-hidden="true"></i></span>
        </td>
    </tr>
    </tbody>
    <tfoot>
    <tr>
        <td class="table-empty" colspan="2">
            <span @click="addLine" class="table-add_line"><font style="cursor: pointer; color: #00c0ef">Add
                Line</font></span>
        </td>
        <td class="table-label">Sub Total</td>
        <td class="table-amount">@{{subTotal}}</td>
    </tr>
    <tr>
        <td class="table-empty" colspan="2"></td>
        <td class="table-label">Discount</td>
        <td class="table-discount" :class="{'table-error': errors.discount}">
            <input type="text" class="table-discount_input" v-model="form.discount">
        </td>
    </tr>
    <tr>
        <td class="table-empty" colspan="2"></td>
        <td class="table-label">Grand Total</td>
        <td class="table-amount">@{{grandTotal}}</td>
    </tr>
    </tfoot>
</table>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 pull-right">
        <div class="form-group">
            <label>Sales Notes</label>
            <textarea class="form-control" rows="3"
                      placeholder="Notes"
                      name="sales_note" v-model="form.sales_note"></textarea>

            <p v-if="errors.sales_note" class="error">@{{errors.sales_note[0]}}</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 pull-right">
        <div class="form-group">
            <label>Terms & Condition</label>
            <textarea class="form-control" rows="3"
                      placeholder="Terms & Condition"
                      name="sales_tnc" v-model="form.sales_tnc"></textarea>

            <p v-if="errors.sales_tnc" class="error">@{{errors.sales_tnc[0]}}</p>
        </div>
    </div>
</div>

resources/views/sales/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sales
            <small>list</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Sales</li>
        </ol>
    </section>

    <section class="content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="clearfix">
                    <a href="/sales/create" class="btn btn-info pull-left"><i class="fa fa-plus"
                                                                              aria-hidden="true"></i> New</a>
                </div>
            </div>
            <div class="panel-body">
                @if($sales->count())
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Sales No.</th>
                            <th>Grand Total</th>
                            <th>Customer Name</th>
                            <th>Sales Date</th>
                            <th>Due Date</th>
                            <th colspan="2">Created At</th>
                            <th colspan="2">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($sales as $sale)
                            <tr>
                                <td>{{$sale->sales_no}}</td>
                                <td>‎৳ {{$sale->grand_total}}</td>
                                <td>{{$sale->sales_customer_name}}</td>
                                <td>{{$sale->sales_date}}</td>
                                <td>{{$sale->due_date}}</td>
                                <td>{{$sale->created_at->diffForHumans()}}</td>
                                <td class="text-left">
                                    <a href="/sales/{{$sale->id}}"
                                       class="btn btn-success btn-sm"><i class="fa fa-search" aria-hidden="true"></i>
                                        View</a>
                                </td>
                                <td>
                                    <a href="/sales/{{$sale->id}}/edit"
                                       class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o"
                                                                         aria-hidden="true"></i> Edit</a>
                                </td>
                                <td>
                                    <form class="form-inline" onsubmit="return confirm('Are you sure?')"
                                          action="/sales/{{$sale->id}}" method="post" class="pull-left">
                                        {{csrf_field()}}
                                        {{method_field('DELETE')}}
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fa fa-btn fa-trash" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                    {{--<form class="form-inline" method="post"
                                          action="{{route('sales.destroy', $sale)}}"
                                          onsubmit="return confirm('Are you sure?')"
                                            >
                                        <input type="hidden" name="_method" value="delete">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fa fa-btn fa-trash" aria-hidden="true"></i>
                                        </button>
                                    </form>--}}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {!! $sales->render() !!}
                @else
                    <div class="invoice-empty">
                        <p class="invoice-empty-title">
                            No sales were created.
                            <a href="/sales/create">Create Now!</a>
                        </p>
                    </div>
                @endif
            </div>
        </div>
    </section>
@endsection

resources/views/sales/print.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Purchase Bill</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="../../bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<section class="content">
    <body onload="window.print();">
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-2">
                <br><img class="img-responsive" src="/dist/img/logo-black.png">
            </div>
            <div class="col-xs-8 text-center">
                <h3 style="color: #00c0ef;">
                    @foreach ($supplier as $object)
                        {{--{{ $object->company_name }}--}}
                        {{ ucwords(trans($object->company_name)) }}
                </h3>
                <h4>House# {{ $object->billing_house }}, Street# {{ $object->billing_street }}</h4>
                <h4>City# {{ $object->billing_city }} , Zip# {{ $object->billing_zip }}
                    , {{$object->billing_country}}</h4>
                <h4>Phone: {{$object->billing_phone}} ,
                    website:
                    <a target="_blank">{{ $object->supplier_website }}</a>
                    @endforeach
                </h4>
            </div>
            <!-- /.col -->
        </div>
        <br><br>

        <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                Bill To
                <address>
                    <strong>{{$purchase->client}}</strong>
                    <br>
                    @foreach ($customer as $co)
                        House# {{ $co->billing_house }} , Street# {{ $co->billing_street }}

                        <br>
                        City# {{ $co->billing_city }} , Zip# {{ $co->billing_zip }}
                        , {{$co->billing_country}}
                        <br>
                        Phone: {{$co->billing_phone}}<br>
                        Email: {{$co->contact_email}}
                    @endforeach
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                Shift To
                <address>
                    <strong>{{$purchase->client}}</strong>
                    <br>
                    @foreach ($customer as $co)
                        House# {{ $co->shipping_house }} , Street# {{ $co->shipping_street }}

                        <br>
                        City# {{ $co->shipping_city }} , Zip# {{ $co->shipping_zip }}
                        , {{$co->shipping_country}}
                        <br>
                        Phone: {{$co->shipping_phone}}<br>
                    @endforeach
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <b>#Purchase - {{$purchase->purchase_no}}</b><br>
                <br>
                <b>Order ID:</b> {{$purchase->purchase_order_number}}<br>
                <b>Payment Due:</b> {{$purchase->due_date}}<br>
                <b>Purchase Reference:</b> {{$purchase->purchase_reference}}
            </div>
            <!-- /.col -->
        </div>

        <hr>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Product Name</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody>
            @foreach($purchase->products as $product)
                <tr>
                    <td class="table-name">{{$product->name}}</td>
                    <td class="table-price">${{$product->price}}</td>
                    <td class="table-qty">{{$product->qty}}</td>
                    <td class="table-total"> ৳ {{$product->qty * $product->price}}</td>
                </tr>
            @endforeach
            </tbody>
            <tfoot>
            <tr>
                <td class="table-empty" colspan="2"></td>
                <td class="table-label">Sub Total</td>
                <td class="table-amount"> ৳ {{$purchase->sub_total}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="2"></td>
                <td class="table-label">Discount</td>
                <td class="table-amount"> ৳ {{$purchase->discount}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="2"></td>
                <td class="table-label">Grand Total</td>
                <td class="table-amount"> ৳ {{$purchase->grand_total}}</td>
            </tr>
            </tfoot>
        </table>
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="col-md-7 form-group pull-left">
                    <br>

                    <p>
                        Thank you for your business!
                        <br>
                        Should you have any enquiries concerning this invoice, please contact
                        <br>
                        <b>{{$purchase->supplier_name}}</b>
                        <br>
                        @foreach($supplier as $object)
                            Voice: {{$object->contact_phone}}
                            <br>
                            Email: {{$object->contact_email}}
                            <br>
                            {{ ucwords(trans($object->company_name)) }}
                            <br>
                            House# {{ $object->billing_house }}, Street# {{ $object->billing_street }}
                            City# {{ $object->billing_city }} , Zip# {{ $object->billing_zip }}
                            , {{$object->billing_country}}
                            <br>
                            Visit Us:
                            <a>{{ $object->supplier_website }}</a>
                        @endforeach
                    </p>
                </div>

                <div class="col-md-5 form-group pull-right">
                    <br><label>___________________________</label> <br>

                    <small class="text-center">Authorized Signature & Date</small>

                </div>
            </div>
        </div>
    </div>
    </body>
</section>

</html>