routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('/item', 'ItemController');
Route::resource('/uom', 'UnitController');
Route::resource('/supplier', 'SupplierController');
Route::resource('/purchase', 'PurchaseController');
Route::resource('/customer', 'CustomerController');
Route::resource('/sales', 'SalesController');
Route::get('/purchase-outstanding','PurchaseController@purchaseOutstanding');
Route::get('/purchase/{id}/print', 'PurchaseController@purchasePrint');
Route::get('/invoice/{id}/print', 'InvoiceController@invoicePrint');
Route::get('/sales-outstanding', 'SalesController@salesOutstanding');
Route::get('/payment-transaction','HomeController@paymentTransaction');
Route::resource('/invoices', 'InvoiceController');
Route::resource('/bills', 'BillController');

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = [
        'invoice_no', 'invoice_date', 'due_date', 'order_number', 'sales_person', 'sub_total', 'discount', 'tnc', 'notes', 'terms',
        'grand_total', 'client',
        'client_address'
    ];

    public function products()
    {
        return $this->hasMany(InvoiceProduct::class);
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Invoice;
use App\InvoiceProduct;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class InvoiceController extends Controller
{
    public function index()
    {
        $invoices = Invoice::orderBy('created_at', 'desc')
            ->paginate(8);

        return view('invoices.index', compact('invoices'));
    }

    public function create()
    {
        $suppliers = DB::table('suppliers')
            ->select('supplier_name')
            ->where('deleted_at', '=', null)
            ->get();
        $customers = DB::table('customers')
            ->select('customer_name')
            ->where('deleted_at', '=', null)
            ->get();

        $items = DB::table('items')
            ->select('item_name', 'item_sales_selling_price', 'item_purchase_selling_price', 'item_sales_tax')
            ->where('deleted_at', '=', null)
            ->get();
        return view('invoices.create', compact('items', 'suppliers', 'customers'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'invoice_no' => 'required|alpha_dash|unique:invoices',
            'client' => 'required|max:255',
            'client_address' => 'required|max:255',
            'invoice_date' => 'required|date_format:Y-m-d',
            'due_date' => 'required|date_format:Y-m-d',
            'discount' => 'required|numeric|min:0',
            'products.*.name' => 'required|max:255',
            'products.*.price' => 'required|numeric|min:1',
            'products.*.qty' => 'required|integer|min:1'
        ]);

        $products = collect($request->products)->transform(function($product) {
            $product['total'] = $product['qty'] * $product['price'];
            return new InvoiceProduct($product);
        });

        if($products->isEmpty()) {
            return response()
            ->json([
                'products_empty' => ['One or more Product is required.']
            ], 422);
        }

        $data = $request->except('products');
        $data['sub_total'] = $products->sum('total');
        $data['grand_total'] = $data['sub_total'] - $data['discount'];

        $invoice = Invoice::create($data);

        $invoice->products()->saveMany($products);

        return response()
            ->json([
                'created' => true,
                'id' => $invoice->id
            ]);
    }

    public function show($id)
    {
        $invoice = Invoice::with('products')->findOrFail($id);

        $supplier = DB::table('suppliers')
            ->join('invoices', 'suppliers.supplier_name', '=', 'invoices.sales_person')
            ->where('invoices.id', '=', $id)
            ->get();

        $customer = DB::table('customers')
            ->join('invoices', 'customers.customer_name', '=', 'invoices.client')
            ->where('invoices.id', '=', $id)
            ->get();

        return view('invoices.show', compact('invoice', 'supplier', 'customer'));
    }

    public function edit($id)
    {
        $suppliers = DB::table('suppliers')
            ->select('supplier_name')
            ->where('deleted_at', '=', null)
            ->get();
        $customers = DB::table('customers')
            ->select('customer_name')
            ->where('deleted_at', '=', null)
            ->get();

        $items = DB::table('items')
            ->select('item_name', 'item_sales_selling_price', 'item_purchase_selling_price', 'item_sales_tax')
            ->get();

        $invoice = Invoice::with('products')->findOrFail($id);

        return view('invoices.edit', compact('invoice', 'items', 'suppliers', 'customers'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'invoice_no' => 'required|alpha_dash|unique:invoices,invoice_no,'.$id.',id',
            'client' => 'required|max:255',
            'client_address' => 'required|max:255',
            'invoice_date' => 'required|date_format:Y-m-d',
            'due_date' => 'required|date_format:Y-m-d',
            'discount' => 'required|numeric|min:0',
            'products.*.name' => 'required|max:255',
            'products.*.price' => 'required|numeric|min:1',
            'products.*.qty' => 'required|integer|min:1'
        ]);

        $invoice = Invoice::findOrFail($id);

        $products = collect($request->products)->transform(function($product) {
            $product['total'] = $product['qty'] * $product['price'];
            return new InvoiceProduct($product);
        });

        if($products->isEmpty()) {
            return response()
            ->json([
                'products_empty' => ['One or more Product is required.']
            ], 422);
        }

        $data = $request->except('products');
        $data['sub_total'] = $products->sum('total');
        $data['grand_total'] = $data['sub_total'] - $data['discount'];

        $invoice->update($data);

        InvoiceProduct::where('invoice_id', $invoice->id)->delete();

        $invoice->products()->saveMany($products);

        return response()
            ->json([
                'updated' => true,
                'id' => $invoice->id
            ]);
    }

    public function destroy($id)
    {
        $invoice = Invoice::findOrFail($id);

        InvoiceProduct::where('invoice_id', $invoice->id)
            ->delete();

        $invoice->delete();

        return redirect()
            ->route('invoices.index');
    }

    public function invoicePrint($id)
    {
        $invoice = Invoice::with('products')->findOrFail($id);

        $supplier = DB::table('suppliers')
            ->join('invoices', 'suppliers.supplier_name', '=', 'invoices.sales_person')
            ->where('invoices.id', '=', $id)
            ->get();

        $customer = DB::table('customers')
            ->join('invoices', 'customers.customer_name', '=', 'invoices.client')
            ->where('invoices.id', '=', $id)
            ->get();

        return view('invoices.print', compact('invoice', 'supplier', 'customer'));

    }
}

resources/views/invoices/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div id="invoice">
            <div class="panel panel-default" v-cloak>
                <div class="panel-heading">
                    <div class="clearfix">
                        <span class="panel-title">Create Invoice</span>
                        <a href="{{route('invoices.index')}}" class="btn btn-default pull-right">Back</a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('invoices.form')
                </div>
                <div class="panel-footer">
                    <a href="{{route('invoices.index')}}" class="btn btn-default">CANCEL</a>
                    <button class="btn btn-success" @click="create" :disabled="isProcessing">CREATE</button>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>

<script src="/js/vue.min.js"></script>
<script src="/js/vue-resource.min.js"></script>
<script type="text/javascript">
    Vue.http.headers.common['X-CSRF-TOKEN'] = '{{csrf_token()}}';

    window._form = {
        invoice_no: '',
        client: '',
        order_number: '',
        sales_person: '',
        tnc: '',
        notes: '',
        terms: '',
        client_address: '',
        title: '',
        invoice_date: '',
        due_date: '',
        discount: 0,
        products: [{
            name: '',
            price: 0,
            qty: 1
        }]
    };
</script>

<script src="/js/app.js"></script>
@endpush

resources/views/invoices/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div id="invoice">
            <div class="panel panel-default" v-cloak>
                <div class="panel-heading">
                    <div class="clearfix">
                        <span class="panel-title">Edit Invoice</span>
                        <a href="{{route('invoices.index')}}" class="btn btn-default pull-right">Back</a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('invoices.form')
                </div>
                <div class="panel-footer">
                    <a href="{{route('invoices.index')}}" class="btn btn-default">CANCEL</a>
                    <button class="btn btn-success" @click="update" :disabled="isProcessing">UPDATE</button>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
<script src="/js/vue.min.js"></script>
<script src="/js/vue-resource.min.js"></script>
<script type="text/javascript">
    Vue.http.headers.common['X-CSRF-TOKEN'] = '{{csrf_token()}}';
    /*window._form = {!!$invoice -> toJson()!!}; //this is correct format*/
    window._form = {
    !!$invoice - > toJson()
    !!
    }
    ;
</script>
<script src="/js/app.js"></script>
@endpush

resources/views/invoices/form.blade.php
<style>
    p {
        color: #ff0000;
    }
</style>
<div class="row">

    <div class="col-sm-4">
        <div class="form-group">
            <label>Invoice No.</label>
            <input type="text" class="form-control" v-model="form.invoice_no">
            <p v-if="errors.invoice_no" class="error">@{{errors.invoice_no[0]}}</p>
        </div>
        <div class="form-group">
            <label>Customer Name</label>
            <select class="form-control" name="client" v-model="form.client">
                <option disabled>Please Select Customer</option>
                @foreach($customers as $customer)
                    <option value="{{$customer->customer_name}}">{{$customer->customer_name}}</option>
                @endforeach
            </select>
            <p v-if="errors.client" class="error">@{{errors.client[0]}}</p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label>Customer Address</label>
            <textarea class="form-control" v-model="form.client_address"></textarea>
            <p v-if="errors.client_address" class="error">@{{errors.client_address[0]}}</p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label>Sales Person</label>
            <select class="form-control" name="supplier_name" v-model="form.sales_person">
                <option disabled>Select Supplier</option>
                @foreach($suppliers as $supplier)
                    <option value="{{$supplier->supplier_name}}">{{$supplier->supplier_name}}</option>
                @endforeach
            </select>
            <p v-if="errors.sales_person" class="error">@{{errors.sales_person[0]}}</p>
        </div>
        <div class="form-group">
            <label>Order Number</label>
            <input type="text" class="form-control" v-model="form.order_number">
            <p v-if="errors.order_number" class="error">@{{errors.order_number[0]}}</p>
        </div>
        <div class="form-group">
            <label>Payment Terms</label>
            <select class="form-control" name="terms" v-model="form.terms">
                <option disabled>Select a Payment Term</option>
                <option>7 days</option>
                <option>10 days</option>
                <option>15 days</option>
                <option>20 days</option>
                <option>30 days</option>
                <option>3 months</option>
                <option>6 months</option>
                <option>1 year</option>
            </select>
            <p v-if="errors.terms" class="error">@{{errors.terms[0]}}</p>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <label>Invoice Date</label>
                <input type="date" class="form-control" v-model="form.invoice_date">
                <p v-if="errors.invoice_date" class="error">@{{errors.invoice_date[0]}}</p>
            </div>
            <div class="col-sm-6">
                <label>Due Date</label>
                <input type="date" class="form-control" v-model="form.due_date">
                <p v-if="errors.due_date" class="error">@{{errors.due_date[0]}}</p>
            </div>
        </div>
    </div>
</div>
<hr>
<div v-if="errors.products_empty">
    <p class="alert alert-danger">@{{errors.products_empty[0]}}</p>
    <hr>
</div>
<table class="table table-bordered table-form">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <tr v-for="product in form.products">
            <td class="table-name" :class="{'table-error': errors['products.' + $index + '.name']}">
                {{--<textarea class="table-control" v-model="product.name"></textarea>--}}

                <select class="form-control" id="name" v-model="product.name">
                    <option disabled>Please Select Item</option>
                    @foreach($items as $item)
                        <option @click="selectItem" value="{{$item->item_sales_selling_price}}"
                        >{{$item->item_name}}</option>
                    @endforeach
                </select>
            </td>
            <td class="table-price" :class="{'table-error': errors['products.' + $index + '.price']}">
                {{--<input type="text" class="table-control"  v-model="product.price">--}}
                <input type="text" class="form-control" v-model="product.price" id="price">
            </td>
            <td class="table-qty" :class="{'table-error': errors['products.' + $index + '.qty']}">
                <input type="text" class="form-control" v-model="product.qty">
            </td>
            <td class="table-total">
                <span class="table-text" id="total">@{{product.qty * product.price}}</span>
            </td>
            <td class="table-remove">
                <span @click="remove(product)" class="table-remove-btn"><i class="fa fa-trash-o"
                                                                           aria-hidden="true"></i></span>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td class="table-empty" colspan="2">
                <span @click="addLine" class="table-add_line"><font style="cursor: pointer; color: #00c0ef">Add
                    Line</font></span>
            </td>
            <td class="table-label">Sub Total</td>
            <td class="table-amount">@{{subTotal}}</td>
        </tr>
        <tr>
            <td class="table-empty" colspan="2"></td>
            <td class="table-label">Discount</td>
            <td class="table-discount" :class="{'table-error': errors.discount}">
                <input type="text" class="table-discount_input" v-model="form.discount">
            </td>
        </tr>
        <tr>
            <td class="table-empty" colspan="2"></td>
            <td class="table-label">Grand Total</td>
            <td class="table-amount">@{{grandTotal}}</td>
        </tr>
    </tfoot>
</table>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 pull-right">
        <div class="form-group">
            <label>Sales Notes</label>
            <textarea class="form-control" rows="3"
                      placeholder="Notes"
                      name="notes" v-model="form.notes"></textarea>
            <p v-if="errors.notes" class="error">@{{errors.notes[0]}}</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 pull-right">
        <div class="form-group">
            <label>Terms & Condition</label>
            <textarea class="form-control" rows="3"
                      placeholder="Terms & Condition"
                      name="tnc" v-model="form.tnc"></textarea>
            <p v-if="errors.tnc" class="error">@{{errors.tnc[0]}}</p>
        </div>
    </div>
</div>

resources/views/invoices/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Invoices
            <small>list</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Invoices</li>
        </ol>
    </section>

    <section class="content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="clearfix">
                    <a href="{{route('invoices.create')}}" class="btn btn-info pull-left"><i class="fa fa-plus"
                                                                                             aria-hidden="true"></i> New</a>
                </div>
            </div>
            <div class="panel-body">
                @if($invoices->count())
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Invoice No.</th>
                            <th>Grand Total</th>
                            <th>Client</th>
                            <th>Invoice Date</th>
                            <th>Due Date</th>
                            <th colspan="2">Created At</th>
                            <th colspan="2">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($invoices as $invoice)
                            <tr>
                                <td>{{$invoice->invoice_no}}</td>
                                <td>‎৳ {{$invoice->grand_total}}</td>
                                <td>{{$invoice->client}}</td>
                                <td>{{$invoice->invoice_date}}</td>
                                <td>{{$invoice->due_date}}</td>
                                <td>{{$invoice->created_at->diffForHumans()}}</td>
                                <td class="text-left">
                                    <a href="{{route('invoices.show', $invoice)}}"
                                       class="btn btn-success btn-sm"><i class="fa fa-search" aria-hidden="true"></i>
                                        View</a>
                                </td>
                                <td>
                                    <a href="{{route('invoices.edit', $invoice)}}"
                                       class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o"
                                                                         aria-hidden="true"></i> Edit</a>
                                </td>
                                <td>
                                    <form class="form-inline" method="post"
                                          action="{{route('invoices.destroy', $invoice)}}"
                                          onsubmit="return confirm('Are you sure?')"
                                            >
                                        <input type="hidden" name="_method" value="delete">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fa fa-btn fa-trash" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {!! $invoices->render() !!}
                @else
                    <div class="invoice-empty">
                        <p class="invoice-empty-title">
                            No Invoices were created.
                            <a href="{{route('invoices.create')}}">Create Now!</a>
                        </p>
                    </div>
                @endif
            </div>
        </div>
    </section>
@endsection

resources/views/invoices/print.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Invoice</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="../../bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<section class="content">
    <body onload="window.print();">
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-2">
                <br><img class="img-responsive" src="/dist/img/logo-black.png">
            </div>
            <div class="col-xs-8 text-center">
                <h3 style="color: #00c0ef;">
                    @foreach ($supplier as $object)
                        {{--{{ $object->company_name }}--}}
                        {{ ucwords(trans($object->company_name)) }}
                </h3>
                <h4>House# {{ $object->billing_house }}, Street# {{ $object->billing_street }}</h4>
                <h4>City# {{ $object->billing_city }} , Zip# {{ $object->billing_zip }}
                    , {{$object->billing_country}}</h4>
                <h4>Phone: {{$object->billing_phone}} ,
                    website:
                    <a target="_blank">{{ $object->supplier_website }}</a>
                    @endforeach
                </h4>
            </div>
            <!-- /.col -->
        </div>
        <br><br>

        <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                Bill To
                <address>
                    <strong>{{$invoice->client}}</strong>
                    <br>
                    @foreach ($customer as $co)
                        House# {{ $co->billing_house }} , Street# {{ $co->billing_street }}

                        <br>
                        City# {{ $co->billing_city }} , Zip# {{ $co->billing_zip }}
                        , {{$co->billing_country}}
                        <br>
                        Phone: {{$co->billing_phone}}<br>
                        Email: {{$co->contact_email}}
                    @endforeach
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                Shift To
                <address>
                    <strong>{{$invoice->client}}</strong>
                    <br>
                    @foreach ($customer as $co)
                        House# {{ $co->shipping_house }} , Street# {{ $co->shipping_street }}

                        <br>
                        City# {{ $co->shipping_city }} , Zip# {{ $co->shipping_zip }}
                        , {{$co->shipping_country}}
                        <br>
                        Phone: {{$co->shipping_phone}}<br>
                    @endforeach
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <b>#Purchase - {{$invoice->purchase_no}}</b><br>
                <br>
                <b>Order ID:</b> {{$invoice->purchase_order_number}}<br>
                <b>Payment Due:</b> {{$invoice->due_date}}<br>
                <b>Purchase Reference:</b> {{$invoice->purchase_reference}}
            </div>
            <!-- /.col -->
        </div>

        <hr>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Product Name</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody>
            @foreach($invoice->products as $product)
                <tr>
                    <td class="table-name">{{$product->name}}</td>
                    <td class="table-price">${{$product->price}}</td>
                    <td class="table-qty">{{$product->qty}}</td>
                    <td class="table-total"> ৳ {{$product->qty * $product->price}}</td>
                </tr>
            @endforeach
            </tbody>
            <tfoot>
            <tr>
                <td class="table-empty" colspan="2"></td>
                <td class="table-label">Sub Total</td>
                <td class="table-amount"> ৳ {{$invoice->sub_total}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="2"></td>
                <td class="table-label">Discount</td>
                <td class="table-amount"> ৳ {{$invoice->discount}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="2"></td>
                <td class="table-label">Grand Total</td>
                <td class="table-amount"> ৳ {{$invoice->grand_total}}</td>
            </tr>
            </tfoot>
        </table>
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="col-md-7 form-group pull-left">
                    <br>

                    <p>
                        Thank you for your business!
                        <br>
                        Should you have any enquiries concerning this invoice, please contact
                        <br>
                        <b>{{$invoice->supplier_name}}</b>
                        <br>
                        @foreach($supplier as $object)
                            Voice: {{$object->contact_phone}}
                            <br>
                            Email: {{$object->contact_email}}
                            <br>
                            {{ ucwords(trans($object->company_name)) }}
                            <br>
                            House# {{ $object->billing_house }}, Street# {{ $object->billing_street }}
                            City# {{ $object->billing_city }} , Zip# {{ $object->billing_zip }}
                            , {{$object->billing_country}}
                            <br>
                            Visit Us:
                            <a>{{ $object->supplier_website }}</a>
                        @endforeach
                    </p>
                </div>

                <div class="col-md-5 form-group pull-right">
                    <br><label>___________________________</label> <br>

                    <small class="text-center">Authorized Signature & Date</small>

                </div>
            </div>
        </div>
    </div>
    </body>
</section>

</html>